# docker container run --name c1 -it --detach python

- name: pre-reqs for community.docker
  hosts: localhost
  tags: prereqs
  tasks:
    - ansible.builtin.pip:
        name: requests

- name: create containers to use as ansible managed nodes
  hosts: localhost
  module_defaults:
    community.docker.docker_container:
      force_kill: true
      state: absent
  tasks:
    - community.docker.docker_container:
        name: "c{{ item }}"
        image: python
        # keep running in background:
        tty: true
        interactive: true
      loop: "{{ range(1,10) }}"
    - community.docker.docker_container:
        name: sleeper
        image: python:3.6
        command: sleep infinity
